### PR TITLE
Add aro_hcp v1alpha1 Root resource

### PR DESCRIPTION
**Pull request by nimrodshn**
Create a new root resource for the `/aro_hcp` service and add a locator with reference to the `/clusters_mgmt/v1/clusters` locator.

This PR is depending on https://github.com/openshift-online/ocm-api-metamodel/pull/210.

### CODE REVIEW

**Comment by nimrodshn** [comment]
Note to self - Need to bump meta-model version

**Comment by tzvatot** [comment]
Why is the path `v1_alpha1` and not `v1alpha1`?

**Comment by nimrodshn** [comment]
> Why is the path `v1_alpha1` and not `v1alpha1`?

Done. thank you!

**Comment by ahitacat** [comment]
To compile this new model we require the metamodel v0.062 https://github.com/openshift-online/ocm-api-model/pull/1010

**Review by zgalor — APPROVED** [review]
lgtm

**Pull request merged**
