### PR TITLE
Trivial: fix space on model

### PR DESCRIPTION
**Pull request by lucasponce**
Hi,
I'm starting to review the repo.
Could I send minor fixes like this one?

Some projects prefer not to add them unless there is a bigger feature/change included; just let me know.

Thanks!

### CODE REVIEW

**Comment by lucasponce** [comment]
I've noticed that the `make lint` on this project fails.
So perhaps the indentation is not enforced?

**Comment by tbrisker** [comment]
@lucasponce i'm not sure GH is displaying the spacing correctly here, it seems to still be off? might be a matter of tabs vs. spaces.

**Comment by renan-campos** [comment]
Tomer's right: the other fields are tabbed whereas this field is using spaces. It may be that in your IDE they appear aligned. Sorry to say this mistake originates from me :/ since then I changed my vim settings so that I can now tell different whitespace apart.

**Comment by renan-campos** [comment]
Oh, I was going to create a code suggestion that replaces the space with the tab, but I don't think its possible in github...

**Comment by lucasponce** [comment]
Perhaps this one is outdated.
I'll try to fix indentation issues on regular PR.
This one as proposed when I was getting familiar with the code.

**Pull request closed without merging**
