### PR TITLE
release 0.0.101 - fix addon installation delete method

### PR DESCRIPTION
**Pull request by ciaranRoche**
Closes JIRA : https://issues.redhat.com/browse/SDA-3255

*Change* 
* fix delete method to correct api endpoint

### CODE REVIEW

**Comment by ciaranRoche** [comment]
\cc @vkareh can you have a look at this, the original delete endpoint was wrong, I think this is the correct method now.

**Comment by vkareh** [comment]
:facepalm: Good catch, thanks for fixing this!

/lgtm

**Comment by ciaranRoche** [comment]
@vkareh i will add the release commit to this PR

**Comment by vkareh** [comment]
will you release the new tag or do you want me to do it?

**Pull request merged**
