### PR TITLE
[OCM-1791] OCM SDK: Release SDK with updated API

### PR DESCRIPTION
**Pull request by Ankit152**
Signed-off-by: Ankit Kurmi <akurmi@redhat.com>

Jira: [OCM-1791](https://issues.redhat.com/browse/OCM-1791)

### CODE REVIEW

**Review by Ankit152 — COMMENTED** [review]
Don't you think we should be using `Version AddonVersion` here instead of `link Version AddonVersion`? 
Ref: https://github.com/openshift-online/ocm-api-model/blob/main/model/addons_mgmt/v1/addon_type.model#L77

**Comment by ashishmax31** [comment]
@Ankit152 Thats how its done for the CS model https://github.com/openshift-online/ocm-api-model/blob/main/model/clusters_mgmt/v1/add_on_type.model#L83.

**Comment by ashishmax31** [comment]
There is something wrong in this MR. The open api document is not getting updated.
Run `make openapi` and check `openapi/addons_mgmt/v1/openapi.json`, This file should have the new endpoints and resources.

**Comment by Ankit152** [comment]
Thanks @ashishmax31 
I will work on the support for package image in addon versions table and once that gets merged, I will update this PR and get it reviewed/merged. 🙂

**Review by ciaranRoche — APPROVED** [review]
lgtm

**Comment by ciaranRoche** [comment]
@Ankit152 before merging can you squash those commits

**Comment by Ankit152** [comment]
@ciaranRoche done

**Pull request merged**
