### PR TITLE
Add version to cloud provider data struct

### PR DESCRIPTION
**Pull request by oriAdler**
Related: [SDA-6766](https://issues.redhat.com/browse/SDA-6766)

### CODE REVIEW

**Comment by oriAdler** [comment]
@zgalor @tbrisker PTAL

Is this addition equivalent to this change in cluster service?
```
type CloudProviderInquiries struct {
	GCP         *GCP         `json:"gcp,omitempty"`
	Region      *CloudRegion `json:"region,omitempty"`
	KeyLocation *string      `json:"key_location,omitempty"`
	KeyRingName *string      `json:"key_ring_name,omitempty"`
	AWS         *AWS         `json:"aws,omitempty"`
-->>    Version     *Version     `json:"version,omitempty"`
}
```

**Comment by tbrisker** [comment]
@oriAdler I don't see this field on the backend, and the issue has no information on why this field is needed or what it's suppose to represent.

**Comment by zgalor** [comment]
> @zgalor @tbrisker PTAL
> 
> Is this addition equivalent to this change in cluster service?
> 
> ```
> type CloudProviderInquiries struct {
> 	GCP         *GCP         `json:"gcp,omitempty"`
> 	Region      *CloudRegion `json:"region,omitempty"`
> 	KeyLocation *string      `json:"key_location,omitempty"`
> 	KeyRingName *string      `json:"key_ring_name,omitempty"`
> 	AWS         *AWS         `json:"aws,omitempty"`
> -->>    Version     *Version     `json:"version,omitempty"`
> }
> ```

yes

**Comment by oriAdler** [comment]
> @oriAdler I don't see this field on the backend, and the issue has no information on why this field is needed or what it's suppose to represent.

You're right, I need to merge this one https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/merge_requests/4601 first to have this field in the backend.

I've added more description to the issue.

**Comment by oriAdler** [comment]
@zgalor @tbrisker https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/merge_requests/4601 is merged now.

**Pull request merged**
