### PR TITLE
Adding cluster ingresses endpoint

### PR DESCRIPTION
**Pull request by zvikorn**
Signed-off-by: Tzvika Avni <tavni@redhat.com>

### CODE REVIEW

**Comment by zvikorn** [comment]
@vkareh Could you please take a look?

**Comment by vkareh** [comment]
Indentation is off, it should be a single tab, but you have 4 spaces. Other than that LGTM :)

**Comment by vkareh** [comment]
hmmm... still looks off. This repo uses only tabs, because of Go conventions, but your changes use spaces instead :/

Make sure you fixup/squash your commits

**Comment by zvikorn** [comment]
I am trying to set my gloand up correctly...

**Comment by vkareh** [comment]
Thanks! LGTM :)

**Pull request merged**
