### PR TITLE
Update changes

### PR DESCRIPTION
**Pull request by tzvatot**
@igoihman PTAL

### CODE REVIEW

**Comment by tzvatot** [comment]
@vkareh @zvikorn @pvasant PTAL

**Comment by vkareh** [comment]
before we merge this we might want to include #231

**Comment by tzvatot** [comment]
> before we merge this we might want to include #231

Done. PreTAL

**Comment by vkareh** [comment]
sorry, we're also missing `- [AMS] Added token authorization endpoint`

**Comment by tzvatot** [comment]
> sorry, we're also missing `- [AMS] Added token authorization endpoint`

Do you mean this? https://github.com/openshift-online/ocm-api-model/pull/230

**Comment by vkareh** [comment]
No, this: #229

**Comment by Lir10** [comment]
No, this https://github.com/openshift-online/ocm-api-model/pull/218 ;)

**Comment by tzvatot** [comment]
@vkareh @Lir10 PreTAL

**Comment by vkareh** [comment]
sorry, @Lir10 is right, my bad

/lgtm

**Pull request merged**
