### PR TITLE
add external resources to add on type model

### PR DESCRIPTION
**Pull request by ciaranRoche**
JIRA - https://issues.redhat.com/browse/SDA-2805

### CODE REVIEW

**Comment by vkareh** [comment]
I think the model attribute name will change based on the latest CS merge request

**Comment by vkareh** [comment]
/lgtm

Let's hold on merging this until we can discuss the model/SDK flow tomorrow

**Comment by ciaranRoche** [comment]
perfect, thanks @vkareh :+1:

**Pull request merged**
