### PR TITLE
[OCM-2150] Change name to StsSupportJumpRole

### PR DESCRIPTION
**Pull request by davidleerh**

### CODE REVIEW

**Review by gdbranco — APPROVED** [review]

**Review by tzvatot — CHANGES_REQUESTED** [review]
You may want to rename the file as well.

**Comment by davidleerh** [comment]
Thank you for the change request @tzvatot 
I totally forgot about that :cry:

**Review by tzvatot — APPROVED** [review]

**Comment by tzvatot** [comment]
LGTM

**Comment by davidleerh** [comment]
moved same changes to https://github.com/openshift-online/ocm-api-model/pull/793
to avoid rebase conflicts introduced

**Pull request closed without merging**
