### PR TITLE
feat(clusters): add domain_prefix field in the cluster's API

### PR DESCRIPTION
**Pull request by machi1990**
Opening as draft until the backend changes are merged

### CODE REVIEW

**Comment by machi1990** [comment]
This needs to be reworked as the name is changed to `domain_prefix`

**Comment by machi1990** [comment]
Once this is merged, I'll followup with the updates of the https://github.com/openshift-online/ocm-api-model/blob/main/CHANGES.md

**Review by ciaranRoche — COMMENTED** [review]
naming is hard :smile: 

/lgtm

**Comment by machi1990** [comment]
Thanks for the review @ciaranRoche

**Pull request merged**
