### PR TITLE
Add Hypershift field for CloudRegion resource to the model

### PR DESCRIPTION
**Pull request by andreadecorte**
Related: SDA-7081

### CODE REVIEW

**Comment by tzvatot** [comment]
LGTM

@zgalor @oriAdler @vkareh @ciaranRoche  I wonder about the field name. Initially "HypershiftEnabled" sounded solid as we have "Enabled" field which is more general. But then I noticed we have "SupprtsMultiAZ" so I'm wondering flavour we should take moving forward. Any recommendations?

**Comment by zgalor** [comment]
> LGTM
> 
> @zgalor @oriAdler @vkareh @ciaranRoche I wonder about the field name. Initially "HypershiftEnabled" sounded solid as we have "Enabled" field which is more general. But then I noticed we have "SupprtsMultiAZ" so I'm wondering flavour we should take moving forward. Any recommendations?

Enabled, and Supports usualy mean different things.
The fact that a feature is supported doesn't mean it's enabled.
If I understand the meaning of that field I think `SupportsHypershift` is more appropriate here

**Comment by andreadecorte** [comment]
> > LGTM
> > @zgalor @oriAdler @vkareh @ciaranRoche I wonder about the field name. Initially "HypershiftEnabled" sounded solid as we have "Enabled" field which is more general. But then I noticed we have "SupprtsMultiAZ" so I'm wondering flavour we should take moving forward. Any recommendations?
> 
> Enabled, and Supports usualy mean different things. The fact that a feature is supported doesn't mean it's enabled. If I understand the meaning of that field I think `SupportsHypershift` is more appropriate here

I agree, that was my initial choice too as it is not something to be enabled in this context. I'll be bold and switch this back to SupportsHypershift in the PR

**Comment by tzvatot** [comment]
> > > LGTM
> > > @zgalor @oriAdler @vkareh @ciaranRoche I wonder about the field name. Initially "HypershiftEnabled" sounded solid as we have "Enabled" field which is more general. But then I noticed we have "SupprtsMultiAZ" so I'm wondering flavour we should take moving forward. Any recommendations?
> > 
> > 
> > Enabled, and Supports usualy mean different things. The fact that a feature is supported doesn't mean it's enabled. If I understand the meaning of that field I think `SupportsHypershift` is more appropriate here
> 
> I agree, that was my initial choice too as it is not something to be enabled in this context. I'll be bold and switch this back to SupportsHypershift in the PR

Looks like the "Supports" is the wording also used in AWS API. For example: https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instance-types.html

**Pull request merged**
