### PR TITLE
[OCM-2111] add organization id to feature_review_request type

### PR DESCRIPTION
**Pull request by ThirumlaDevi**
This PR adds the organization id to the feature_review_request model which is required for ocm-cs integration.
API reference to the feature_review endpoint --> [reference](https://api.openshift.com/?urls.primaryName=Accounts%20management%20service#/default/post_api_authorizations_v1_feature_review)

### CODE REVIEW

**Comment by miguelsorianod** [comment]
The change looks good to me :+1: .

I understand from this the next step is that we will generate the changes so they are included in the SDK right?

A minor comment too:

Commit messages should be written in imperative present tense. Avoid using the past or other tenses. The reason for that is that you should see a commit log as a set of steps that if you apply a given commit 'x' will happen.

**Comment by lucasponce** [comment]
cc @ciaranRoche or @gdbranco can you please final review and merge?

I don't have rights on this repo

**Comment by ThirumlaDevi** [comment]
Yes @miguelsorianod the request builder from the sdk currently doesn't take this as input which is necessary for ocm cs to migrate to feature review api

**Review by tzvatot — APPROVED** [review]
LGTM

**Comment by ThirumlaDevi** [comment]
@tzvatot Post merge there is not tag created pointing to this change, could you please trigger the respective github action or please let me know on what i must do from my end to do so?

**Comment by tzvatot** [comment]
It is done manually. See contribution md file I linked on slack.

I'm AFK, but surely some of the other maintainers can create the tag.

**Comment by ciaranRoche** [comment]
ill create the tag  for you now

**Pull request merged**
