### PR TITLE
Add FullNames and LimitScope to statusboard statuses

### PR DESCRIPTION
**Pull request by djberg96**
This updates the statuses and statusupdates in statusboard to match the updates to the openapi config that now allows `full_names` and `limit_scope` parameters.

### CODE REVIEW

**Comment by djberg96** [comment]
@jhernand Look ok?

**Comment by jhernand** [comment]
Yes @djberg96, looks good to me. Feel free to merge and release.

**Comment by djberg96** [comment]
@jhernand I don't want to merge my own PR, and I don't know how to release.

**Comment by jhernand** [comment]
@djberg96 to release you need to update the CHANGES.md file and then push the tag. You have all the required permissions. It is explained here: https://github.com/openshift-online/ocm-sdk-go/blob/main/CONTRIBUTING.md#releasing-a-new-ocm-api-model-version .

**Comment by jhernand** [comment]
@zgalor @tzvatot I see that you released a few minutes ago. You may want to coordinate with @djberg96 if you are going to update the SDK.

**Comment by djberg96** [comment]
@jhernand Ok, step 1: https://github.com/openshift-online/ocm-api-model/pull/547

**Pull request merged**
