### PR TITLE
add Search parameter to status board product, application, service

### PR DESCRIPTION
**Pull request by smcavey**
Add Search parameter to add TSL support to Status Board for [OSDEV-1284]https://issues.redhat.com/browse/OSDEV-1284l) and [OSDEV-1281](https://issues.redhat.com/browse/OSDEV-1281l). ocm-sdk-go [update](https://github.com/openshift-online/ocm-sdk-go/pull/858)

### CODE REVIEW

**Review by marek-veber — APPROVED** [review]
/lgtm

**Review by marek-veber — APPROVED** [review]

**Comment by ciaranRoche** [comment]
@smcavey can you split the changes into two commits, we want to keep the updates to the changes log in their own commit for the history please :pray: 

will merge then

**Comment by smcavey** [comment]
@ciaranRoche Updated, thanks :)

**Review by ciaranRoche — APPROVED** [review]
LGTM

**Pull request merged**
