### PR TITLE
Add 'fields' parameter to all list-requests

### PR DESCRIPTION
**Pull request by gshilin-sdb**

### CODE REVIEW

**Comment by gshilin-sdb** [comment]
@igoihman PTAL

**Comment by gshilin-sdb** [comment]
Fixed indentation

**Comment by vkareh** [comment]
Thanks! /lgtm

**Comment by vkareh** [comment]
@gshilin-sdb - A conflict happened when merging #189 - could you rebase this, please?

**Comment by gshilin-sdb** [comment]
done

**Pull request merged**
