### PR TITLE
OCM-15 : Add MachineTypeRootVolume to MachinePool

### PR DESCRIPTION
**Pull request by leseb**
This will allow us to set a Size and/or IOPS for a given root volume.

### CODE REVIEW

**Comment by leseb** [comment]
@ciaranRoche @tzvatot @gdbranco PTAL

**Comment by leseb** [comment]
Another option if we don't want to use the AWS struct is to put `RootVolume` in `MachinePool` like so:

```
class MachinePool {
...
	// The machine root volume capabilities.
	RootVolume MachineTypeRootVolume
...
...
}
```


Thoughts?

**Comment by leseb** [comment]
I remember @vkareh saying that `AWSMachinePool` and `AWS` structs were generally used for specific parameters. Perhaps this could tilt the balance in favor of `MachineTypeRootVolume`.

**Comment by tzvatot** [comment]
LGTM

@vkareh LGTY?

**Comment by vkareh** [comment]
LGTM

**Comment by romfreiman** [comment]
hmm why it does not merge?

**Pull request merged**
