### PR TITLE
Update CHANGES.md ver 0.0.193

### PR DESCRIPTION
**Pull request by djberg96**

### CODE REVIEW

**Comment by djberg96** [comment]
I added the changes from @renan-campos as well.

**Comment by djberg96** [comment]
@jhernand, @tzvatot It looks like 0.0.193 was released today, but this wasn't added. Is there an issue?

**Comment by tzvatot** [comment]
> @jhernand, @tzvatot It looks like 0.0.193 was released today, but this wasn't added. Is there an issue?

We needed a new version. This one is not merged yet.

**Comment by tzvatot** [comment]
@djberg96 can you please resolve conflicts and push again?

**Comment by djberg96** [comment]
@tzvatot Done!

**Comment by tzvatot** [comment]
@djberg96 @renan-campos the content is in 193 and it needs to update 193 content instead.

**Comment by djberg96** [comment]
@tzvatot I thought there already was a 0.0.193 release. Ok, I've updated it.

**Comment by tzvatot** [comment]
LGTM

**Pull request merged**
